/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://syu54xrbibfabivxast3rzwkje.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dqwwk4phbrb3npvt5duwdpggum",
    "aws_cognito_identity_pool_id": "us-east-1:9fbc7798-625d-4328-a246-bcdd5b0a85a0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yr6Ei1KUb",
    "aws_user_pools_web_client_id": "66b7vf6ps7e5kpqsu7re3lsq8b",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
