/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateBizOwner = /* GraphQL */ `
  subscription OnCreateBizOwner {
    onCreateBizOwner {
      id
      ownerID
      username
      role
      status
      lname
      fname
      street
      unit
      city
      state
      zip
      questionnaireId
      businessName
      businessDBAName
      businessLogo
      businessEmail
      businessPhone
      businessURL
      practiceType
      mobileClinicType
      missionStatement
      visionStatement
      aboutBusiness
      ownerBiodata
      businessLicenseNumber
      businessLicenseAcquiredDate
      businessLicenseExpiryDate
      professionalLicenseName
      professionalLicenseNumber
      professionalLicenseAcquiredDate
      professionalLicenseExpiryDate
      hygieneAssociationMembership
      hygieneAssociationMembershipExpiryDate
      aDAMembership
      aDAMembershipExpiryDate
      continuingEducationHours
      continuingEducationHoursExpiryDate
      cPRNumber
      cPRNumberExpiryDate
      financialInstituteName
      primaryDentist
      primaryDentistPhone
      primaryDentistEmail
      secondaryDentist
      secondaryDentistPhone
      secondaryDentistEmail
      lawyerName
      lawyerPhone
      lawyerEmail
      accountantName
      accountantPhone
      accountantEmail
      websiteDesigner
      websiteSupport
      targetMarket
      socialMediaMarketing
      oldfashionedMarketing
      businessReviewsURL
      module1ActionsCompleted
      module2ActionsCompleted
      module3ActionsCompleted
      module4ActionsCompleted
      module5ActionsCompleted
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateBizOwner = /* GraphQL */ `
  subscription OnUpdateBizOwner {
    onUpdateBizOwner {
      id
      ownerID
      username
      role
      status
      lname
      fname
      street
      unit
      city
      state
      zip
      questionnaireId
      businessName
      businessDBAName
      businessLogo
      businessEmail
      businessPhone
      businessURL
      practiceType
      mobileClinicType
      missionStatement
      visionStatement
      aboutBusiness
      ownerBiodata
      businessLicenseNumber
      businessLicenseAcquiredDate
      businessLicenseExpiryDate
      professionalLicenseName
      professionalLicenseNumber
      professionalLicenseAcquiredDate
      professionalLicenseExpiryDate
      hygieneAssociationMembership
      hygieneAssociationMembershipExpiryDate
      aDAMembership
      aDAMembershipExpiryDate
      continuingEducationHours
      continuingEducationHoursExpiryDate
      cPRNumber
      cPRNumberExpiryDate
      financialInstituteName
      primaryDentist
      primaryDentistPhone
      primaryDentistEmail
      secondaryDentist
      secondaryDentistPhone
      secondaryDentistEmail
      lawyerName
      lawyerPhone
      lawyerEmail
      accountantName
      accountantPhone
      accountantEmail
      websiteDesigner
      websiteSupport
      targetMarket
      socialMediaMarketing
      oldfashionedMarketing
      businessReviewsURL
      module1ActionsCompleted
      module2ActionsCompleted
      module3ActionsCompleted
      module4ActionsCompleted
      module5ActionsCompleted
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteBizOwner = /* GraphQL */ `
  subscription OnDeleteBizOwner {
    onDeleteBizOwner {
      id
      ownerID
      username
      role
      status
      lname
      fname
      street
      unit
      city
      state
      zip
      questionnaireId
      businessName
      businessDBAName
      businessLogo
      businessEmail
      businessPhone
      businessURL
      practiceType
      mobileClinicType
      missionStatement
      visionStatement
      aboutBusiness
      ownerBiodata
      businessLicenseNumber
      businessLicenseAcquiredDate
      businessLicenseExpiryDate
      professionalLicenseName
      professionalLicenseNumber
      professionalLicenseAcquiredDate
      professionalLicenseExpiryDate
      hygieneAssociationMembership
      hygieneAssociationMembershipExpiryDate
      aDAMembership
      aDAMembershipExpiryDate
      continuingEducationHours
      continuingEducationHoursExpiryDate
      cPRNumber
      cPRNumberExpiryDate
      financialInstituteName
      primaryDentist
      primaryDentistPhone
      primaryDentistEmail
      secondaryDentist
      secondaryDentistPhone
      secondaryDentistEmail
      lawyerName
      lawyerPhone
      lawyerEmail
      accountantName
      accountantPhone
      accountantEmail
      websiteDesigner
      websiteSupport
      targetMarket
      socialMediaMarketing
      oldfashionedMarketing
      businessReviewsURL
      module1ActionsCompleted
      module2ActionsCompleted
      module3ActionsCompleted
      module4ActionsCompleted
      module5ActionsCompleted
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onCreateRegistrationQns = /* GraphQL */ `
  subscription OnCreateRegistrationQns {
    onCreateRegistrationQns {
      id
      questionnaireId
      passion
      othersInterest
      planB
      pricePoint
      competition
      growBusiness
      insuranceNeeds
      costOfEntry
      monthlyLivingExpenses
      readyAndDriven
      additionalNotes1
      additionalNotes2
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateRegistrationQns = /* GraphQL */ `
  subscription OnUpdateRegistrationQns {
    onUpdateRegistrationQns {
      id
      questionnaireId
      passion
      othersInterest
      planB
      pricePoint
      competition
      growBusiness
      insuranceNeeds
      costOfEntry
      monthlyLivingExpenses
      readyAndDriven
      additionalNotes1
      additionalNotes2
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteRegistrationQns = /* GraphQL */ `
  subscription OnDeleteRegistrationQns {
    onDeleteRegistrationQns {
      id
      questionnaireId
      passion
      othersInterest
      planB
      pricePoint
      competition
      growBusiness
      insuranceNeeds
      costOfEntry
      monthlyLivingExpenses
      readyAndDriven
      additionalNotes1
      additionalNotes2
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
  }
`;
